import fs from 'fs';
import path from 'path';
import { getTemplatePath } from '../utils/paths.js';
import { parseNestedYamlValue } from '../utils/yaml.js';
import { log } from '../utils/logger.js';

const START_MARKER = '<!-- konbini:sdd:start -->';
const END_MARKER = '<!-- konbini:sdd:end -->';

export interface ClaudeMdConfig {
  language: string;
  path: string;
}

export function detectLanguage(content: string): string {
  if (!content) return 'en';
  // Count Japanese characters (hiragana, katakana, CJK unified ideographs)
  const japaneseChars = content.match(/[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FFF]/g);
  const totalChars = content.replace(/\s/g, '').length;
  if (totalChars === 0) return 'en';
  const ratio = (japaneseChars?.length ?? 0) / totalChars;
  return ratio > 0.1 ? 'ja' : 'en';
}

export function buildSection(templateContent: string, version: string): string {
  const content = templateContent.replace(/\{\{VERSION\}\}/g, version);
  return [
    START_MARKER,
    `<!-- Generated by konbini v${version} — DO NOT EDIT THIS SECTION MANUALLY -->`,
    content,
    END_MARKER,
  ].join('\n');
}

export function injectSection(existingContent: string, section: string): string {
  if (!existingContent) return section;

  const hasStart = existingContent.includes(START_MARKER);
  const hasEnd = existingContent.includes(END_MARKER);

  // Both markers present — replace between them
  if (hasStart && hasEnd) {
    const startIdx = existingContent.indexOf(START_MARKER);
    const endIdx = existingContent.indexOf(END_MARKER) + END_MARKER.length;
    const before = existingContent.slice(0, startIdx);
    const after = existingContent.slice(endIdx);
    return before + section + after;
  }

  // Broken state (only one marker) — remove orphaned marker before appending
  if (hasStart || hasEnd) {
    const cleaned = existingContent
      .split('\n')
      .filter(line => !line.includes(START_MARKER) && !line.includes(END_MARKER))
      .join('\n');
    return cleaned + '\n\n' + section;
  }

  // No markers — append
  return existingContent + '\n\n' + section;
}

function getVersion(): string {
  const pkgPath = path.resolve(getTemplatePath('..'), 'package.json');
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    return pkg.version ?? '0.0.0';
  } catch {
    return '0.0.0';
  }
}

function loadTemplate(language: string): string | null {
  const supported = ['en', 'ja'];
  const lang = supported.includes(language) ? language : 'en';
  const templatePath = getTemplatePath(`claude-md/${lang}.md`);
  try {
    return fs.readFileSync(templatePath, 'utf-8');
  } catch {
    return null;
  }
}

export function injectClaudeMd(projectRoot: string, config: ClaudeMdConfig): void {
  const template = loadTemplate(config.language);
  if (!template) {
    log.error(`CLAUDE.md テンプレートが見つかりません: ${config.language}`);
    return;
  }

  const version = getVersion();
  const section = buildSection(template, version);
  const claudeMdPath = path.resolve(projectRoot, config.path);

  try {
    fs.mkdirSync(path.dirname(claudeMdPath), { recursive: true });

    let existing = '';
    if (fs.existsSync(claudeMdPath)) {
      existing = fs.readFileSync(claudeMdPath, 'utf-8');
    }

    const result = injectSection(existing, section);
    fs.writeFileSync(claudeMdPath, result);
    log.success(`CLAUDE.md にSDDルールを注入しました (${config.language})`);
  } catch (e) {
    log.error(`CLAUDE.md の書き込みに失敗しました: ${e}`);
  }
}

export function readClaudeMdConfig(aoYamlContent: string): ClaudeMdConfig {
  const language = parseNestedYamlValue(aoYamlContent, 'claude_md.language') ?? 'en';
  const claudeMdPath = parseNestedYamlValue(aoYamlContent, 'claude_md.path') ?? 'CLAUDE.md';
  return { language, path: claudeMdPath };
}
